---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings exists
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Kubernetes APT GPG key
  become: yes
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{KUBERNETES_VERSION}}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository
  become: yes
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{KUBERNETES_VERSION}}/deb/ /
    filename: "kubernetes"
    state: present

- name: Add CRI-O Kubic repository GPG key
  become: yes
  shell: |
    curl -fsSL https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{CRIO_VERSION}}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add CRI-O Kubic repository for CRI-O version
  become: yes
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{CRIO_VERSION}}/deb/ /
    state: present
    filename: "cri-o"


- name: Update APT cache
  become: yes
  apt:
    update_cache: yes

- name: Install CRI-O and Kubernetes dependencies
  apt:
    name:
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
    state: present
    

- name: Enable and start CRI-O service
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: yes

- name: Reload systemd to apply override
  systemd:
    daemon_reload: yes

- name: Hold Cri-o and Kubernetes packages
  apt:
    name: "{{ item }}"
    state: fixed
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - cri-o


- name: Enable IP forwarding for Kubernetes
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Ensure br_netfilter module is loaded
  become: yes
  modprobe:
    name: br_netfilter
    state: present   

- name: Disable swap
  command: swapoff -a
  become: yes
