- hosts: all
  become: yes
  vars:
    CRIO_VERSION: "v1.34"
    KUBERNETES_VERSION: "v1.34"
  roles:
    - common

- hosts: master
  become: yes
  roles:
    - master

- hosts: workers
  become: yes
  roles:
    - worker

