---
- name: Join worker nodes to cluster
  become: yes
  shell: "{{ hostvars['kube_master']['join_cmd'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

# - name: Join worker to cluster
#   shell: sh /tmp/join-command.sh
